from abc import ABC, abstractmethod
from typing import Optional

class IUnitOfWork(ABC):
    @abstractmethod
    def __enter__(self) -> "IUnitOfWork": ...
    @abstractmethod
    def __exit__(self, exc_type, exc, tb) -> Optional[bool]: ...
    @abstractmethod
    def commit(self) -> None: ...
    @abstractmethod
    def rollback(self) -> None: ...
